server:
 port: 8013
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        ConnectTimeOut: 5000
        ReadTimeOut: 5000
# springboot 2.x 默认只开启了info、health的访问，*代表开启所有访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000   #默认
        timeout:
          enabled: true
      #serverMethod:
      #  execution:
      #    isolation:
      #      thread:
      #        timeoutInMilliseconds: 10000
  threadpool:
    default:
      coreSize: 1 #并发执行的最大线程数，默认10
      maxQueueSize: -1 #BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 3