server:
  port: 8106
spring:
  application:
    name: eureka-client-producer # 实例名称，唯一标识
eureka:
  client:
    service-url: # 指向注册中心
      defaultZone: http://localhost:8101/eureka/
feign:
  hystrix:  #开启熔断
    enabled: true
