server:
  port: 9000 # 端口
spring:
  profiles:
    active: native
  application:
    name: config-server # 实例名称
  cloud:
    config:
      server:
        native:
          search-locations: D:/tmp
        #git:
        #  #uri: https://gitee.com/GeorgeChan/spring-cloud-parent.git # git仓库的地址
        #  uri: https://gitee.com/wasd2587/springDemo.git # git仓库的地址
        #  search-paths: config-file/dev,config-file/pro,config-file/test  # git仓库地址下的相对地址，可以配置多个，用,分割。
        #  username: wasd2587  #用户名
        #  password: a3388110
  # rabbitmq 配置
  rabbitmq:
    host: 101.42.251.121
    port: 5672
    username: mqtest
    password: a3388110
# 配置注册中心
eureka:
  client:
    service-url: # 注册中心地址
      defaultZone: http://localhost:8761/eureka/

#  springboot 2.x 默认只开启了info、health的访问，*代表开启所有访问
management:
  endpoints:
    web:
      exposure:
        include: "*"
